# Generated by Django 6.1 on 2026-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='qualification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
