# Generated by Django 6.1 on 2026-08-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_studentuser_experience_studentuser_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='status',
            field=models.CharField(default='Pending', max_length=20, null=True),
        ),
    ]
