# Generated by Django 6.1 on 2026-08-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_applyjob_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
