# Generated by Django 6.1 on 2026-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_applyjob_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
